apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex05_deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ex_05
  template:
    metadata:
      labels:
        app: ex_05
    spec:
      volumes:
        - name: volume-type-emptydir
          emptyDir:
            sizeLimit: "500M"

        - name: volume-type-hostpath
          hostPath:
            path: /data-app-ex05
            type: DirectoryOrCreate

      containers:
      - name: ex_05
        volumeMounts:          
          - mountPath: /data-partagees
            name: volume-type-hostpath

        image: hanryos/ex05
        env:
          - name: STORY_FILE
            value: "/app/story/"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
