apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex05-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ex-05
  template:
    metadata:
      labels:
        app: ex-05
    spec:
      volumes:
        - name: volume-type-hostpath
          hostPath:
            path: /data-app-ex05
            type: DirectoryOrCreate

      containers:
      - name: ex-05
        volumeMounts:          
          - mountPath: /app/story
            name: volume-type-hostpath

        image: hanryos/ex05
        env:
          - name: STORY_FOLDER
            value: "/story"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
